language: csharp

matrix:
  include:
    - os: osx
      mono: 4.2.0
    - os: osx
      mono: 4.4.2
    - os: osx
      mono: latest
  # The whole build matrix fails when any individual builds fail
  # (except those which have been allowed with allow_failures).
  fast_finish: true

# Compilation on Linux fails because of lack of installed PCL libraries.  We should reference the FSharp.Core package as a dependency
# to fix this.
#    - os: linux
#      dist: trusty
#      sudo: required
#      mono: 4.4.2


env:
  global:
    - MONO_MANAGED_WATCHER=disabled

script:
  - ./build.sh CleanInternetCaches && ./build.sh All

branches:
  except:
    - gh-pages
    - release
