language: objective-c

env:
  global:
    - MONO_VERSION=4.2.0

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - ls -R /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/ 

script: 
  - ./build.sh CleanInternetCaches && ./build.sh All

branches:
  except:
    - gh-pages
    - release